---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	preprocessor(preprocessor)
	observer(observer)
	bank_adder(bank_adder)
	retrieval(retrieval)
	__end__([<p>__end__</p>]):::last
	__start__ --> preprocessor;
	bank_adder --> retrieval;
	observer --> bank_adder;
	preprocessor --> observer;
	retrieval --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
